-- CREATE TABLE account (
--                          id int NOT NULL AUTO_INCREMENT,
--                          name varchar(255) NOT NULL,
--                          usdt_balance DECIMAL(19,8),
--                          eth_balance DECIMAL(19,8),
--                          btc_balance DECIMAL(19,8),
--                          PRIMARY KEY (id)
-- );
--default user with 50000USDT balance
INSERT INTO account (id, name,usdt_balance, eth_balance, btc_balance) VALUES (1,'demo', 50000, 0,0);

-- CREATE TABLE oracle (
--                        id int NOT NULL AUTO_INCREMENT,
--                        ticker varchar(3) NOT NULL,
--                        buy_price DECIMAL(19,8),
--                        sell_price DECIMAL(19,8),
--                        PRIMARY KEY (id)
-- );
--
-- CREATE TABLE history (
--                         id int NOT NULL AUTO_INCREMENT,
--                         ticker varchar(3) NOT NULL,
--                         type varchar(3) NOT NULL,
--                         price DECIMAL(19,8),
--                         fiat_amount DECIMAL(19,8),
--                         crypto_amount DECIMAL(19,8),
--                         transaction_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
--                         PRIMARY KEY (id)
-- );